# image: python:latest
image: python:3.4
services:
  - mysql:latest
stages:
  - prepare
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  MYSQL_DATABASE: "pub_download"
  MYSQL_ROOT_PASSWORD: "pub_pass"

cache:
  paths:
    - .cache/pip
    - venv/

install:
  stage: prepare
  script:
  - install_dependencies
  artifacts:
    paths:
    - public


test:
  stage: test
  script:
  - install_dependencies
  - pip install tox flake8  # you can also use tox
  - tox -e py34,flake8

pages:
  stage: test
  dependencies:
   - prepare

  image: mysql
  script:
  - install_dependencies
  - make_documentation
  artifacts:
    paths:
    - public
  only:
  - master


# run:
#   script:
#   # - python setup.py bdist_wheel
#   - pwd
  
#   # an alternative approach is to install and run:
#   #- pip install dist/*
#   # run the command here
#   artifacts:
#     paths:
#     - dist/*.whl


.auto_devops: &auto_devops |
  function install_dependencies() {
    python -V               # Print out python version for debugging
    pip install virtualenv
    virtualenv venv --python=python3
    source venv/bin/activate
    pip install -r requeriments.txt
  }
  function make_documentation() {
    source venv/bin/activate
    pip install sphinx sphinx-rtd-theme
    cd docs ; make html
    mv build/html/ ../public/
  }
before_script:
  - *auto_devops

mysql_build:
  stage: prepare
  image: mysql
  script:
  - mysql --version
  - echo "SELECT 'OK';" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"


