# image: python:latest
image: python:3.4
services:
  - mysql:latest
stages:
  - prepare
  - test


# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  MYSQL_DATABASE: "pub_download"
  MYSQL_ROOT_PASSWORD: "pub_pass"

# cache:
#   paths:
#     - .cache/pip
#     - venv/

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv --python=python3
  - source venv/bin/activate
  - pip install -r requeriments.txt

mysql_build:
  stage: prepare
  image: mysql
  script:
  - mysql --version
  - echo "SELECT 'OK';" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"

test:
  stage: test
  script:
  # - python setup.py test
  - pwd
  - pip install tox flake8  # you can also use tox
  - tox -e py34,flake8


# run:
#   script:
#   # - python setup.py bdist_wheel
#   - pwd
  
#   # an alternative approach is to install and run:
#   #- pip install dist/*
#   # run the command here
#   artifacts:
#     paths:
#     - dist/*.whl


# pages:
#   script:
#   - pip install sphinx sphinx-rtd-theme
#   - cd docs ; make html
#   - mv build/html/ ../public/
#   artifacts:
#     paths:
#     - public
#   only:
#   - master
